# Generated by Django 5.1.2 on 2024-10-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidoc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor_reviewed',
        ),
        migrations.AddField(
            model_name='session',
            name='doctor_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
