# Generated by Django 5.1.2 on 2024-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidoc_app', '0002_remove_report_doctor_reviewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
